version: "3.9"

services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=database
    